name: Xorcist4
title: XORcist4 Laboratory
description: I will be adding blogs about write-ups and boxes ive done along with things i am currently working on.
tags:
  - blog
  - write-ups
  - trainings
  - gaming
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: imoonwalker@igothacked.wtf
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
